# Site settings
title: 波纹科技
email: kefu@bowenpay.com
description: > # this means to ignore newlines until "baseurl:"
  北京市朝阳区广渠路36号首城国际B座908
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bowenpay.com" # the base hostname & protocol for your site
twitter_username: bowenpay
github_username:  bowenpay

# Build settings
markdown: kramdown
